-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 21:16:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Nombre` VARCHAR(40) NOT NULL,
  `Ubicacion` VARCHAR(45) NOT NULL,
  `CodPostal` INT NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unifamiliar` (
  `Numero` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `AñoConstruccion` INT NOT NULL,
  `Nro_Habitantes` INT NOT NULL,
  `Nombre_Zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`, `Calle`),
  INDEX `Nombre_Zona_idx` (`Nombre_Zona` ASC) VISIBLE,
  CONSTRAINT `Nombre_Zona`
    FOREIGN KEY (`Nombre_Zona`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `Numero` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `AñoConstruccion` INT NOT NULL,
  `Nro_Habitantes` INT NOT NULL,
  `Nombre_Zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`, `Calle`),
  INDEX `Nombre_Zona_idx` (`Nombre_Zona` ASC) VISIBLE,
  CONSTRAINT `Nombre_Zona`
    FOREIGN KEY (`Nombre_Zona`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `Nro_Piso` INT NOT NULL,
  `Letra` VARCHAR(10) NOT NULL,
  `Numero` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `Nro_Habitantes` INT NOT NULL,
  PRIMARY KEY (`Nro_Piso`, `Letra`, `Numero`, `Calle`),
  INDEX `Numero_idx` (`Numero` ASC) VISIBLE,
  INDEX `Calle_idx` (`Calle` ASC) VISIBLE,
  CONSTRAINT `Numero`
    FOREIGN KEY (`Numero`)
    REFERENCES `mydb`.`Bloque` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Calle`
    FOREIGN KEY (`Calle`)
    REFERENCES `mydb`.`Bloque` (`Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona-Posee-Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona-Posee-Unifamiliar` (
  `Dni` VARCHAR(10) NOT NULL,
  `Uni_Numero` INT NOT NULL,
  `Uni_Calle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dni`, `Uni_Numero`, `Uni_Calle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona-Posee-Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona-Posee-Piso` (
  `Dni` VARCHAR(10) NOT NULL,
  `Piso_Nro_Piso` INT NOT NULL,
  `Piso_Letra` VARCHAR(10) NOT NULL,
  `Piso_Numero` INT NOT NULL,
  `Piso_Calle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dni`, `Piso_Nro_Piso`, `Piso_Letra`, `Piso_Numero`, `Piso_Calle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `Dni` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` FLOAT NULL,
  `Uni_Numero` INT NOT NULL,
  `Uni_Calle` VARCHAR(45) NOT NULL,
  `Piso_Nro_Piso` INT NOT NULL,
  `Piso_Letra` VARCHAR(10) NOT NULL,
  `Piso_Numero` INT NOT NULL,
  `Piso_Calle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dni`),
  INDEX `Uni_Numero_idx` (`Uni_Numero` ASC) VISIBLE,
  INDEX `Uni_Calle_idx` (`Uni_Calle` ASC) VISIBLE,
  INDEX `Piso_Nro_Piso_idx` (`Piso_Nro_Piso` ASC) VISIBLE,
  INDEX `Piso_Letra_idx` (`Piso_Letra` ASC) VISIBLE,
  INDEX `Piso_Numero_idx` (`Piso_Numero` ASC) VISIBLE,
  INDEX `Piso_Calle_idx` (`Piso_Calle` ASC) VISIBLE,
  CONSTRAINT `Uni_Numero`
    FOREIGN KEY (`Uni_Numero`)
    REFERENCES `mydb`.`Persona-Posee-Unifamiliar` (`Uni_Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Uni_Calle`
    FOREIGN KEY (`Uni_Calle`)
    REFERENCES `mydb`.`Persona-Posee-Unifamiliar` (`Uni_Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Piso_Nro_Piso`
    FOREIGN KEY (`Piso_Nro_Piso`)
    REFERENCES `mydb`.`Persona-Posee-Piso` (`Piso_Nro_Piso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Piso_Letra`
    FOREIGN KEY (`Piso_Letra`)
    REFERENCES `mydb`.`Persona-Posee-Piso` (`Piso_Letra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Piso_Numero`
    FOREIGN KEY (`Piso_Numero`)
    REFERENCES `mydb`.`Persona-Posee-Piso` (`Piso_Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Piso_Calle`
    FOREIGN KEY (`Piso_Calle`)
    REFERENCES `mydb`.`Persona-Posee-Piso` (`Piso_Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
