-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 21:18:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivero` (
  `Localizacion` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Localizacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `CodZona` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Localizacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodZona`),
  INDEX `Localizacion_idx` (`Localizacion` ASC) VISIBLE,
  CONSTRAINT `Localizacion`
    FOREIGN KEY (`Localizacion`)
    REFERENCES `mydb`.`Vivero` (`Localizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `DNI` VARCHAR(30) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Sueldo` FLOAT NOT NULL,
  `NSegSocial` FLOAT NOT NULL,
  `FechaInicio` VARCHAR(45) NOT NULL,
  `FechaFin` VARCHAR(45) NULL,
  `CodigoZona` INT NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `CodZona_idx` (`CodigoZona` ASC) VISIBLE,
  CONSTRAINT `CodZona`
    FOREIGN KEY (`CodigoZona`)
    REFERENCES `mydb`.`Zona` (`CodZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` VARCHAR(10) NOT NULL,
  `CodFid` VARCHAR(45) NOT NULL,
  `Bonificacion` FLOAT NOT NULL,
  `VolumenMensual` FLOAT NOT NULL,
  `FechaNac` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`, `CodFid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Fecha` VARCHAR(10) NOT NULL,
  `CodBarras` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Stock` INT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `CodZona` INT NOT NULL,
  PRIMARY KEY (`CodBarras`),
  INDEX `CodZona_idx` (`CodZona` ASC) VISIBLE,
  CONSTRAINT `CodZona`
    FOREIGN KEY (`CodZona`)
    REFERENCES `mydb`.`Zona` (`CodZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `CodPedidio` INT NOT NULL,
  `Importe` INT NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  `CodBarras` VARCHAR(45) NOT NULL,
  `DNI Cliente` VARCHAR(45) NOT NULL,
  `DNI Empleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodPedidio`),
  INDEX `DNI_idx` (`DNI Cliente` ASC) VISIBLE,
  INDEX `DNI Empleado_idx` (`DNI Empleado` ASC) VISIBLE,
  INDEX `CodigoBarras_idx` (`CodBarras` ASC) VISIBLE,
  CONSTRAINT `DNI Cliente`
    FOREIGN KEY (`DNI Cliente`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNI Empleado`
    FOREIGN KEY (`DNI Empleado`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodigoBarras`
    FOREIGN KEY (`CodBarras`)
    REFERENCES `mydb`.`Producto` (`CodBarras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
